import React from "react";

const AboutMeDescription = () => {
  return (
    <div>
      HELLO I AM ARMOND AND I LOVE WEB DEVHELLO I AM ARMOND AND I LOVE WEB DEVHELLO I AM ARMOND AND
      I LOVE WEB DEVHELLO I AM ARMOND AND I LOVE WEB DEVHELLO I AM ARMOND AND I LOVE WEB DEVHELLO I
      AM ARMOND AND I LOVE WEB DEVHELLO I AM ARMOND AND I LOVE WEB DEVHELLO I AM ARMOND AND I LOVE
      WEB DEVHELLO I AM ARMOND AND I LOVE WEB DEVHELLO I AM ARMOND AND I LOVE WEB DEVHELLO I AM
      ARMOND AND I LOVE WEB DEV
    </div>
  );
};

export default AboutMeDescription;
